base/urls.py
from django.urls import path,include
from base import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("lobby/<int:room_id>/",views.Lobby,name="lobby"),
    path("",views.Home,name="home"),
    path("login/",views.Login,name="login"),
    path("logout/",views.Logout,name="logout"),
    path("register/",views.Register,name="register"),
    path("send-message/",views.SendMessage,name="send-message"),
    path("add-chat/",views.AddChat,name="add-chat"),
    path("edit-chat/<int:pk>/",views.EditChat,name="edit-chat"),
    path("add-friend/<str:text>",views.AddFriend,name="add-friend"),
    path("add-remove-friend/<int:pk>",views.AddRemoveFriend,name="add-remove-friend"),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webSockets/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=False,blank=False)
    profile_code = models.CharField(max_length=8,null=False,blank=False)
    profile_photo = models.ImageField(null=False,blank=False,default='profile_pics/default_profile_pic.jpg',upload_to='profile_pics')
    friends = models.ManyToManyField('self',related_name='users_friends')
    bio = models.CharField(max_length=160,null=True,blank=True,default='Not any information was given.')

    def __str__(self):
        return str(self.user.username)


class Room(models.Model):
    room_name = models.CharField(null=False,blank=False,max_length=100,verbose_name="Room Name")
    room_photo = models.ImageField(null=False,blank=False,default='room_pics/default_room_pic.png',upload_to='room_pics',verbose_name="Room Photo")
    profiles = models.ManyToManyField(Profile,related_name="Members")
    room_admins = models.ManyToManyField(Profile,verbose_name="Rooms admins",related_name="Admins")

    def __str__(self):
        return self.room_name

    def RoomSecurity(self,request):
        if request.user.is_anonymous or get_object_or_404(Profile,user=request.user) not in self.profiles.all():
            return False
        else:
            return True


class Message(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=False,blank=False,related_name='profile')
    text = models.TextField(null=False,blank=False)
    room = models.ForeignKey(Room,null=False,blank=False,on_delete=models.CASCADE,related_name='room')
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

base/forms.py
from dataclasses import field, fields
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render,redirect


class RegisterForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        for fields in self.fields:
            self.fields[fields].widget.attrs.update({'class':'form-control'})

class ChatAddForm(forms.ModelForm):
    
    class Meta:
        model = Room
        fields = '__all__'

base/views.py
from urllib import response
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.shortcuts import redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from base.forms import ChatAddForm, RegisterForm
from base.models import Message, Profile, Room
from django.http import HttpResponse
from django.contrib import messages
import json
from django.core import serializers
from django.http import HttpResponse

@login_required(login_url='/login/')
def Home(request):
    
    profile = get_object_or_404(Profile,user=request.user)
    rooms_all = Room.objects.all()
    rooms = []
    for i in rooms_all:
        if profile in i.profiles.all():
            rooms.append(i)


    if request.method=="POST":
        print(request.POST.get('search_text'))
        return redirect('add-friend',request.POST.get('search_text'))

    context = {
        'rooms':rooms,
    }
    return render(request,"base/index.html",context)


def Login(request):
    if request.user.is_authenticated:
        return redirect("lobby")


    if request.method=="POST":
        username1 = request.POST.get('username')
        if len(User.objects.filter(username=username1))>0:
            username1 = request.POST.get('username')
        else:
            if len(User.objects.all().filter(email=username1)) > 0:
                username1 = User.objects.get(email=username1).username
        password = request.POST.get('password')
        

        person = authenticate(
            request,username=username1, password=password)

        if person is not None:
            login(request, person)
            messages.success(request,'<div class="message btn btn-success position-fixed me-3 mb-3 end-0 bottom-0">Logged in successfully.</div>')
            return redirect("home")

    return render(request,"base/login.html")


@login_required(login_url='/login/')
def Lobby(request,room_id):
    room = get_object_or_404(Room,id=room_id)
    if not room.RoomSecurity(request):
        return render(request,"base/404.html")
    room_messages = Message.objects.filter(room=room)
    context={
        'room':room,
        'room_messages':room_messages
    }
    return render(request,"base/lobby.html",context)


@login_required(login_url='/login/')
def AddChat(request):
    form = ChatAddForm()
    profiles = []
    rooms_all = Room.objects.all()
    user_profile = get_object_or_404(Profile,user=request.user)
    rooms = []
    for i in rooms_all:
        if user_profile in i.profiles.all():
            rooms.append(i)

    for i in rooms:
        for profile in i.profiles.all():
            if profile not in profiles:
                profiles.append(profile)

    profiles.remove(user_profile)

    if request.method=="POST":
        form = ChatAddForm(request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            form.save_m2m()
            messages.success(request,'<div class="message btn btn-success position-fixed me-3 mb-3 end-0 bottom-0">Added a new chat successfully.</div>')
            return redirect("home")
        else:
            print("non-valid")
    context = {
        'form':form,
        'user_profile':user_profile
    }
    return render(request,"base/add-chat.html",context)


@login_required(login_url='/login/')
def EditChat(request,pk):
    room = get_object_or_404(Room,id=pk)
    rooms_profiles = room.profiles.all()
    rooms_admins = room.room_admins.all()
    form = ChatAddForm(instance=room)
    profiles = []
    rooms_all = Room.objects.all()
    user_profile = get_object_or_404(Profile,user=request.user)
    rooms = []
    
    for i in rooms_all:
        if user_profile in i.profiles.all():
            if i not in rooms:
                rooms.append(i)
        if user_profile in i.room_admins.all():
            if i not in rooms:
                rooms.append(i)

    for i in room.profiles.all():
        profiles.append(i)
    profiles.remove(user_profile)

    if request.method=="POST":
        form = ChatAddForm(data=request.POST,files=request.FILES,instance=room)
        if form.is_valid():
            form.save()
            form.save_m2m()
            messages.success(request,'<div class="message btn btn-success position-fixed me-3 mb-3 end-0 bottom-0">'+ request.POST.get('room_name') +' successfully updated.</div>')
            return redirect("edit-chat",room.id)
    
    context = {
        'form':form,
        'profiles':profiles,
        'rooms_profiles':rooms_profiles,
        'user_profile':user_profile,
        'room':room
    }
    
    return render(request,"base/edit-chat.html",context)


@login_required(login_url='/login/')
def Logout(request):
    logout(request)
    messages.success(request,'<div class="message btn btn-success position-fixed me-3 mb-3 end-0 bottom-0">Başarıyla çıkış yapıldı.</div>')
    return redirect("home")


@login_required(login_url='/login/')
def SendMessage(request):
    room_id = request.POST.get('room_id')
    text = request.POST.get('text')

    Message.objects.create(
        profile = get_object_or_404(Profile,user=request.user),
        room = get_object_or_404(Room,id=room_id),
        text = text,
    )

    return HttpResponse("messi")


def Register(request):
    if request.user.is_authenticated:
        return redirect("home")
    form = RegisterForm()
    
    if request.method == 'POST': 
        dizi1=[]
        for i in User.objects.all():
            dizi1.append(i.username.lower())
        if request.POST['username'].lower() in dizi1:
            messages.error(request, 'Girdiğiniz kullanıcı adı kullanımda.')
            return redirect('register')
        
        
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'<div class="message btn btn-success position-fixed me-3 mb-3 end-0 bottom-0">Registered successfully.</div>')
            Profile.objects.update_or_create(
                user=User.objects.get(username = request.POST['username']),
                bio=None,
                profile_photo=None,
                profile_code=None,
            )
            return redirect('login')
        else:
            messages.error(request, '<div class="message btn btn-danger position-fixed me-3 mb-3 end-0 bottom-0">Couldnt register successfully.</div>')

    context = {
        'form': form,
    }
    return render(request, 'base/register.html', context)

@login_required(login_url='/login/')
def AddFriend(request,text):
    user_profile = Profile.objects.get(user=request.user)
    search_profiles = Profile.objects.filter(profile_code__icontains=text)
    if request.method=="POST":
        return redirect('add-friend',request.POST.get('search_text'))

    context = {
        'profiles' : search_profiles,
        'user_profile' : user_profile
    }
    return render(request,"base/add-friend.html",context)


def AddRemoveFriend(request,pk):
    user_profile = Profile.objects.get(user=request.user)
    profile = get_object_or_404(Profile,id=pk)
    if profile in user_profile.friends.all():
        user_profile.friends.remove(get_object_or_404(Profile,id=pk))
    else:
        user_profile.friends.add(get_object_or_404(Profile,id=pk))
    print(profile)
    return redirect("add-friend",profile.profile_code)

# @login_required(login_url='/login/')
# def AddFriendFetch(request):
#     text = request.POST.get('text').lower()
#     profiles = []
#     if text!=None:
#         for i in Profile.objects.all():
#             print(i.user.username.lower(),i.profile_code.lower())
#             if text in  i.user.username.lower():
#                 if i not in profiles:
#                     profiles.append(i)
#             if text in  i.profile_code.lower():
#                 if i not in profiles:
#                     profiles.append(i)
#     dizi = []
#     for i in profiles:
#         dizi.append({'username':i.user.username,'id':i.id})
    
#     return HttpResponse(json.dumps(dizi))  

base/templates/base/add-chat.html
{% extends "base/base.html" %} {% block title %}Add Chat{% endblock title %} {% load crispy_forms_tags %} {% block content %}
<div class="container-fluid container-md mt-5">
  <div class="shadow rounded-3 p-3">
    <h4 class="text-center">Add Chat</h4>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{form|crispy}}
      <label for="id_profiles" class="requiredField mt-4">
        Users in the chat<span class="asteriskField">*</span>
      </label>
      <select
        name="profiles"
        class="selectmultiple form-control"
        id="id_profiles"
        multiple=""
      >
        {% for profile in user_profile.friends.all %}
          <option value="{{profile.id}}">{{profile.user.username}}</option>
        {% endfor %}
      </select>
      <div class="text-center mt-4">
        <input type="submit" value="Add Chat" class="btn btn-success" />
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block script %}
<script>
  $("#id_room_photo").addClass("form-control");
  $(".requiredField").addClass("mt-4");
  $("#div_id_profiles").remove();
  $("#div_id_room_admins").remove();
</script>
{% endblock %}

base/templates/base/add-friend.html
{% extends "base/base.html" %} 
{% block title %}Add Friend{% endblock title %} 
{% block content %}
<div class="container mt-4">
    <div class="shadow rounded-3 px-1 py-2 my-3 d-flex align-items-center">  
        <div class="row justify-content-between" style="width: 100%">
            <div class="col-auto">
                <div class="d-flex align-items-center">
                    <i class="fa-solid fa-comments ps-2 text-primary"></i>
                    <p class="ms-3 fw-bold">{{request.user.username}}</p>
                </div>
            </div>
            <div class="col-auto">
                <a href="{% url 'home' %}" class="d-flex align-items-center text-decoration-none">
                    <i class="fa-solid fa-person-booth"></i>
                    <p class="ms-2">Rooms</p>
                </a>
            </div>
            <div class="col-auto">
                <a href="{% url 'logout' %}" class="text-primary">
                    <i class="fa-solid fa-arrow-right-from-bracket" title="Logout"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="shadow rounded-3 p-3">
        <form method="post">
            {% csrf_token %}
            <label for="search">Users Code</label>
            <div class="row align-items-center">
            <div class="col">
                <input type="search" id="search" placeholder="Search for a user..." name="search_text" required class="search form-control">
            </div>
            <div class="col-auto">
                <button class="btn btn-outline-dark">
                    <i class="fa-solid fa-search"></i>
                </button>
            </div>
            </div>
        </form>
    </div>
    {{user_profile.}}
    <div class="users bg-white shadow-lg rounded-3 p-4 mt-5">
        {% if profiles %}
            {% for profile in profiles %}
            <div class="row align-items-center">
                <div class="col">
                    <h5>{{profile.user.username}}</h5>
                </div>
                <div class="col-auto">
                    {% if profile in user_profile.friends.all %}
                            <a href="{% url 'add-remove-friend' profile.id %}">
                                <i class="fa-solid fa-xmark fa-lg text-danger" title="Add friend"></i>
                            </a>
                        {% else %}
                            <a href="{% url 'add-remove-friend' profile.id %}">
                                <i class="fa-solid fa-check fa-lg text-success" title="Remove friend"></i>
                            </a>
                    {% endif %}
                </div>
                <div class="col-auto">

                </div>
            </div>
            {% endfor %}
        {% else %}
            <h5 class="text-center">Not any profiles were found.</h5>
        {% endif %}
    </div>
</div>
{% endblock %}

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/fontawesome.min.js"
      integrity="sha512-j3gF1rYV2kvAKJ0Jo5CdgLgSYS7QYmBVVUjduXdoeBkc4NFV4aSRTi+Rodkiy9ht7ZYEwF+s09S43Z1Y+ujUkA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    {% for message in messages %}
      {{message|safe}}
    {% endfor %}
    {% block content %} {% endblock %}
    {% block script %} {% endblock %}
    <script>
      $(".message").delay(3000).fadeOut(1000)
    </script>
  </body>
</html>

base/templates/base/edit-chat.html
{% extends "base/base.html" %} 
{% block title %}Add Chat{% endblock title %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container-fluid container-md mt-5">
    <div class="shadow rounded-3 p-3">
        <h4 class="text-center">Add Chat</h4>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form|crispy}}
            <label for="id_profiles" class="requiredField mt-4">
                Users in the chat<span class="asteriskField">*</span> 
            </label>
            <select name="profiles" class="selectmultiple form-control"  id="id_profiles" multiple=""> 
                {% for profile in user_profile.friends.all %}
                    {% if profile in rooms_profiles %}
                        <option value="{{profile.id}}" selected>{{profile.user.username}}</option> 
                    {% else %}
                        <option value="{{profile.id}}">{{profile.user.username}}</option> 
                    {% endif %}
                {% endfor %}
            </select>   
            <label for="id_admins" class="requiredField mt-4">
              Admins of the chat<span class="asteriskField">*</span>
            </label>
            <select
              name="room_admins"
              class="selectmultiple form-control"
              id="id_admins"
              multiple=""
            >
            
              {% for profile in profiles %}
                {% if profile in room.room_admins.all %}
                    <option value="{{profile.id}}" selected>{{profile.user.username}}</option> 
                {% else %}
                    <option value="{{profile.id}}">{{profile.user.username}}</option> 
                {% endif %}
              {% endfor %}
            </select>
            <div class="text-center mt-4">
                <input type="submit" value="Add Chat" class="btn btn-success">
            </div>
        </form>
    </div>
</div>
{% endblock content %}
{% block script %}
<script>
    $("#id_room_photo").addClass("form-control")
    $(".requiredField").addClass("mt-4")
    $("#div_id_profiles").hide();
    $("#div_id_room_admins").hide();
</script>
{% endblock %}

base/templates/base/index.html
{% extends "base/base.html" %} 
{% block title %}Lobby{% endblock title %} 
{% block content %}
<div class="container mt-4">
    <div class="shadow rounded-3 p-3">
        <form method="post">
            {% csrf_token %}
            <label for="search">Users Code</label>
            <div class="row align-items-center">
            <div class="col">
                <input type="search" id="search" placeholder="Search for a user..." name="search_text" required class="search form-control">
            </div>
            <div class="col-auto">
                <button class="btn btn-outline-dark">
                    <i class="fa-solid fa-search"></i>
                </button>
            </div>
            </div>
        </form>
    </div>
    <div class="shadow rounded-3 px-1 py-2 my-3 d-flex align-items-center">  
        <div class="row justify-content-between" style="width: 100%">
            <div class="col-auto">
                <div class="d-flex align-items-center">
                    <i class="fa-solid fa-comments ps-2 text-primary"></i>
                    <p class="ms-3 fw-bold">{{request.user.username}}</p>
                </div>
            </div>
            <div class="col-auto">
                <a href="{% url 'add-chat' %}" class="d-flex align-items-center text-decoration-none">
                    <i class="fa-solid fa-comment-medical ps-2 text-primary"></i>
                    <p class="ms-2">Add a chat</p>
                </a>
            </div>
            <div class="col-auto">
                <a href="{% url 'logout' %}" class="text-primary">
                    <i class="fa-solid fa-arrow-right-from-bracket" title="Logout"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="shadow rounded-3 p-3 friends">
        {% for room in rooms %}
            <div class="friends__friend">
                <a href="{% url 'lobby' room.id %}" class="row align-items-center text-dark text-decoration-none">
                    <div class="col">
                        <div class="d-flex align-items-center">
                            <img src="{{room.room_photo.url}}" alt="profile_picture" title="Profile pic" />
                            <h5>{{room.room_name}}</h5>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fa-solid fa-chevron-right" title="Chat"></i>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(".friends__friend").last().css("border-bottom","0")
</script>
{% endblock %}

base/templates/base/lobby.html
{% extends "base/base.html" %} {% block title %}Lobby{% endblock title %} 
{% block content %}
<div class="container-fluid">
    <div class="category shadow rounded-3 py-2 px-3">  
        <div class="row justify-content-between align-items-center" style="width: 100%">
            <div class="col-auto">
                <div class="d-flex align-items-center">
                    <i class="fa-solid fa-comments fa-lg ps-2 text-primary"></i>
                    <div class="ms-3">
                        <p class="fw-bold">{{room.room_name}}</p>
                        <small>{{request.user.username}}</small>
                    </div>
                    <div class="ms-3" style="cursor: pointer" onclick="toggle_settings()">
                        <i class="fa-solid fa-ellipsis"></i>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <a href="{% url 'logout' %}" class="text-primary">
                    <i class="fa-solid fa-arrow-right-from-bracket fa-lg" title="Logout"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="settings shadow rounded-3 p-3 my-4" style="display: none;">
        <h5>Users of the room</h5>
        <hr>
        {% for i in room.profiles.all %}
            <p>{{i}}</p>
        {% endfor %}
    </div>
    <div class="chat shadow rounded-3">
        <div class="chat__go_back shadow-sm border-bottom bg-light px-3 py-1">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <a href="{% url 'home' %}">
                        <i class="fa-solid fa-arrow-left"></i>
                    </a>
                </div>
                <div class="col-auto">
                    <a href="{% url 'edit-chat' room.id %}">
                        <i class="fa-solid fa-pen"></i>
                    </a>
                </div>
            </div>
            
        </div>
        <div class="p-3 chat__messages">
                    {% for mess in room_messages %}
                        {% if mess.profile.user == request.user %}
                            <div class="chat__message_right shadow-sm">
                            <div class="d-flex align-items-center">
                                <p class="fw-bold">{{mess.profile.user.username}}</p>
                                <p class="dot">•</p>
                                <p class="time">{{mess.create|time:"h:i a"}}</p>
                            </div>
                            <p>{{mess.text}}</p>
                            </div>
                        {% else %}
                            <div class="chat__message_left shadow-sm">
                            <div class="d-flex align-items-center">
                                <p class="fw-bold">{{mess.profile.user.username}}</p>
                                <p class="dot">•</p>
                                <p class="time">{{mess.create|time:"h:i a"}}</p>
                            </div>
                            <p>{{mess.text}}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
        </div>
    </div>
    <form onsubmit="send_message(event)">
                {% csrf_token %}
                <div class="chat__message_send mt-2">
                    <div class="row">
                    <div class="col">
                        <input type="text" class="form-control message_text" placeholder="Your message..." required />
                    </div>
                    <div class="col-auto">
                        <input type="submit" class="btn btn-secondary" value="Send" />
                    </div>
                    </div>
                </div>
    </form>
</div>

{% endblock content %}
{% block script %}
<script type="text/javascript">

    

    let url = `ws://${window.location.host}/ws/socket-server/{{room.id}}/`;

    const chatSocket = new WebSocket(url);

    chatSocket.onmessage = function(e){
        let data = JSON.parse(e.data);
        console.log(data);
        if(data.type=='botjoinmessagge'){
            if (data.sender != "{{request.user.username}}"){
                $('.chat__messages').append(
                    `
                    <div class="chat__message_left shadow-sm">
                        <div class="d-flex align-items-center">
                            <p class="fw-bold">${data.user}</p>
                            <p class="dot">•</p>
                            <p class="time">{% now "h:i a" %}</p>
                        </div>
                        <p>${data.message}</p>
                    </div>
                    `
                )
            }
            
            else{
                $('.chat__messages').append(
                    `
                    <div class="chat__message_left shadow-sm">
                        <div class="d-flex align-items-center">
                            <p class="fw-bold">${data.user}</p>
                            <p class="dot">•</p>
                            <p class="time">{% now "h:i a" %}</p>
                        </div>
                        <p>Welcome to chat!</p>
                    </div>
                    `
                )
            }
        }
        else if(data.type=='botleavemessagge'){
            $('.chat__messages').append(
                `
                <div class="chat__message_left shadow-sm">
                    <div class="d-flex align-items-center">
                        <p class="fw-bold">${data.user}</p>
                        <p class="dot">•</p>
                        <p class="time">{% now "h:i a" %}</p>
                    </div>
                    <p>${data.message}</p>
                </div>
                `
            )
        }
        else if(data.type=='chat'){
            if (data.user=="{{request.user.username}}"){
                $('.chat__messages').append(
                    `
                    <div class="chat__message_right shadow-sm">
                        <div class="d-flex align-items-center">
                            <p class="fw-bold">${data.user}</p>
                            <p class="dot">•</p>
                            <p class="time">{% now "h:i a" %}</p>
                        </div>
                        <p>${data.message}</p>
                    </div>
                    `
                )
            }

            else{
                $('.chat__messages').append(
                `
                <div class="chat__message_left shadow-sm">
                    <div class="d-flex align-items-center">
                        <p class="fw-bold">${data.user}</p>
                        <p class="dot">•</p>
                        <p class="time">{% now "h:i a" %}</p>
                    </div>
                    <p>${data.message}</p>
                </div>
                `
            )
            }
        }
        
        document.querySelector(".chat").scrollTop =
            document.querySelector(".chat").scrollHeight;
    }
    
    async function send_message(event){
        event.preventDefault();
        let message = $(".message_text").val();
        chatSocket.send(JSON.stringify({
            'username':'{{request.user.username}}',
            'message':message,
            'room':'{{room.id}}',
        }))
        $(".message_text").val("");


        let form_data = new FormData();
        form_data.append('text', message);
        form_data.append('csrfmiddlewaretoken', "{{csrf_token}}");
        form_data.append('room_id', '{{room.id}}');
        let response = await fetch(window.location.origin+"/send-message/",{
            method: "POST",
            credentials: 'same-origin',
            headers: { "X-CSRFToken": "{{csrf_token}}" },
            body: form_data,
        });
    }
    

    function toggle_settings(){
        $(".settings").toggle(400);
    }
</script>
{% endblock %}

base/templates/base/login.html
{% extends "base/base.html" %} {% block title %}Lobby{% endblock title %} 
{% block content %}
<div class="container-fluid container-md">
    <div class="bg-light shadow rounded-3 p-4 mt-5">
        <h4 class="mt-3 text-center fw-bold">Login</h4>
        <form method="post">
            {% csrf_token %}
            <label for="username" class="mt-3">Username</label>
            <input type="text" class="form-control" id="username" name="username" required />
            <label for="password" class="mt-4">Password</label>
            <input type="password" class="form-control" id="password" name="password" required />
            <div class="text-center mt-4">
                <input type="submit" value="Login" class="btn btn-primary" />
                <a href="{% url 'register' %}" class="btn btn-secondary ms-3">Register</a>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
{% block script %}
{% endblock %}